2024-04-05 16:36:47.784734: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2024-04-05 16:36:47.785106: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/accounts/projects/jsteinhardt/akommula/.local/lib/python3.8/site-packages/transformers/utils/hub.py:124: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
[nltk_data] Downloading package wordnet to
[nltk_data]     /accounts/projects/jsteinhardt/akommula/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /accounts/projects/jsteinhardt/akommula/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     /accounts/projects/jsteinhardt/akommula/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /accounts/projects/jsteinhardt/akommula/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     /accounts/projects/jsteinhardt/akommula/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /accounts/projects/jsteinhardt/akommula/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     /accounts/projects/jsteinhardt/akommula/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /accounts/projects/jsteinhardt/akommula/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     /accounts/projects/jsteinhardt/akommula/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
/accounts/projects/jsteinhardt/akommula/.local/lib/python3.8/site-packages/datasets/table.py:1421: FutureWarning: promote has been superseded by mode='default'.
  table = cls._concat_blocks(blocks, axis=0)
Repo card metadata block was not found. Setting CardData to empty.
Downloading shards:   0%|          | 0/3 [00:00<?, ?it/s]Downloading shards: 100%|██████████| 3/3 [00:00<00:00, 1062.12it/s]
Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]Loading checkpoint shards:  33%|███▎      | 1/3 [00:03<00:06,  3.40s/it]Loading checkpoint shards:  67%|██████▋   | 2/3 [00:06<00:03,  3.39s/it]Loading checkpoint shards: 100%|██████████| 3/3 [00:09<00:00,  3.24s/it]Loading checkpoint shards: 100%|██████████| 3/3 [00:09<00:00,  3.28s/it]
Traceback (most recent call last):
  File "failure_transfer.py", line 222, in <module>
    instance.pipeline()
  File "/accounts/projects/jsteinhardt/akommula/LLM_failures/failure_transfer/translation_pipeline.py", line 153, in pipeline
    answers = self.interacter.answer_questions(questions, extract_answers)
  File "/accounts/projects/jsteinhardt/akommula/LLM_failures/failure_transfer/interact_mistral.py", line 40, in answer_questions
    self.model.to(device)
  File "/accounts/projects/jsteinhardt/akommula/.local/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2556, in to
    return super().to(*args, **kwargs)
  File "/accounts/projects/jsteinhardt/akommula/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
  File "/accounts/projects/jsteinhardt/akommula/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/accounts/projects/jsteinhardt/akommula/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/accounts/projects/jsteinhardt/akommula/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/accounts/projects/jsteinhardt/akommula/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
  File "/accounts/projects/jsteinhardt/akommula/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 224.00 MiB. GPU 0 has a total capacty of 23.68 GiB of which 15.00 MiB is free. Including non-PyTorch memory, this process has 23.66 GiB memory in use. Of the allocated memory 23.46 GiB is allocated by PyTorch, and 1.14 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
